name: Daily Auto Run

on:
  schedule:
    # 每天UTC时间22:30运行(北京时间06:30)
    - cron: '30 22 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager pillow
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    - name: Run script
      env:
        DOUYIN_COOKIE: ${{ secrets.DOUYIN_COOKIE }}
        USER_CONFIG_JSON: ${{ secrets.USER_CONFIG_JSON }}
      run: python xuhuohua.py

    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: output-logs
        path: |
          *.log
          screenshots/
          *.png
